import SaleRibbon from "@/components/sale-ribbon"

import Footer from "../components/layout/footer"
import Header from "../components/layout/header"
import "./globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <SaleRibbon />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
